### ISSUE TITLE
Program, access out of array bounds.

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#1]
https://github.com/ArtemGomer/LabsNsu/blob/ac2ec3c2f220b756cc0abb788534691de9b9802a/BoierMour.c#L33

**Comment by sergio-nsk** [comment]
У тебя в цикле и i, и j могут достигать нуля, поэтому индекс массива может получиться -1.

**Comment by ArtemGomer** [comment]
Изменил проверку , убрал лишнюю переменную.

**Comment by sergio-nsk** [comment]
Возвращаю оценку 4.
