### ISSUE TITLE
stack-buffer-overflow LAB7(Calc).c:160

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#10]
https://github.com/ArtemGomer/LabsNsu/blob/dcd8e99e86eab39a72166c964b0e725cc94019ed/LAB7(Calc).c#L160

`stack-buffer-overflow LAB7(Calc).c:160:13`
На втором тесте получилось обращению к массиву по индексу -1.
`op->opers[-1]`

**Comment by ArtemGomer** [comment]
В 83 строке вместо && стоял &. Скорее всего в этом была ошибка

**Comment by sergio-nsk** [comment]
Ты прав, ошибка была в этом.
