### ISSUE TITLE
Control may reach end of non-void function

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#11]
https://github.com/ArtemGomer/LabsNsu/blob/53bfb95b3dd70f0c0a5577bd62cb64f852eb261e/LAB7(Calc).c#L209

Что вернёт функция, если ни одно условие не выполнено?

**Comment by ArtemGomer** [comment]
Функция prior не может получить на вход символы не  "+","-","*","/". Поэтому она в любом случае вернет значение.(Надеюсь я вообще понял смысл ошибки)

**Comment by sergio-nsk** [comment]
1. Документации на функцию `prior` у тебя нет написано, поэтому нужно предполагать, что любой символ допустим на входе.
2. Компилятор об этом ничего не знает, поэтому он ругается.
3. Входные параметры публичных функций должны проверяться хотя бы в дебаг-режиме. Ты же не объявил её `static`. Так как мы не проходили дебаг, их нужно проверять всегда.
4. Контрольная проверка в конце для того, чтобы не забыть добавить приоритет будущих новых операций
```
  assert(0);
  return 0;
```

**Comment by ArtemGomer** [comment]
Хорошо. Объясните это завтра на парах , пожалуйста)
