### ISSUE TITLE
'shift' as pointer is odd

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#4]
https://github.com/ArtemGomer/LabsNsu/blob/dea9aec5cbb68f2abb1ea3f114af68ca027fa3d7/LAB2(Boyer-Mour).c#L40

Везде используется только *shift после инициализации указателя. Может быть указатель здесь не нужен совсем?

**Comment by ArtemGomer** [comment]
Исправлено)
