### ISSUE TITLE
getchar is too slow.

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#5]
https://github.com/ArtemGomer/LabsNsu/blob/dea9aec5cbb68f2abb1ea3f114af68ca027fa3d7/LAB2(Boyer-Mour).c#L43

Почему здесь сразу не прочить бы fgets(..., *shift, stdin)? Ну и shift до цикла сделать сразу strlen(shablon). Не обязательно иметь буфер-слайдер размером strlen(shablon). Можно побольше. Тогда memove будет вызываться меньшее число раз.

Так же strlen(shablon) - медленная, и ёе вычисление в цикле многократно замедляет работу программы.

**Comment by ArtemGomer** [comment]
Переделано

**Comment by sergio-nsk** [comment]
Круто! За 1,5 сек теперь проходит 19 тест.
