### ISSUE TITLE
Unused variables.

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/LabsNsu#6]
https://github.com/ArtemGomer/LabsNsu/blob/7d09ff0c3dd72376a6c685b90cc9b9fb93331d0f/LAB2(Boyer-Mour).c#L38

LAB2(Boyer-Mour).c:38:7: warning: unused variable 'k' [-Wunused-variable]
        char k;
             ^
LAB2(Boyer-Mour).c:39:6: warning: unused variable 'i' [-Wunused-variable]
        int i = 0, blink = 0,sdvig[256] = {0}, shift = 0;
            ^

**Comment by ArtemGomer** [comment]
Убрано)
